base_url = "https://clip.chzzfly.com"
[book]
title = "Chzz's Clip"
description = "Chzz's Clip"
src = "content"
language = "zh"
authors = ["Chzz"]

[output.html]
git-repository-url = "https://github.com/chzzfly/clip"
edit-url-template = "https://github.com/chzzfly/clip/edit/main/{path}"

[output.html.search]
enable = false

[output.markdown]
enable = true

[mail]
# false will diasble mail sending
enable = false
from_email = "mail@chzzfly.com"
from_name = "chzz"
# you can set the mailjet contact list id here
# mailjet_contact_list_id = "17669"
# or directly set the to_email, seperated by comma
# or your can also set the environment variable TO_EMAIL
to_email = ""
